/****************************************************************************
**
** Copyright (C) 2010 Andriy Kovalchuk, Vyacheslav Levytskyy,
** Igor Samolyuk, Valentyn Yanchuk (aka "Hermitech Laboratory")
**
** All rights reserved.
** Contact: Hermitech Laboratory (info@mmlsoft.com)
**
** This file is a part of the Formulator MathML Editor project
** (http://www.mmlsoft.com).
**
** Commercial Usage
** Licensees holding valid Formulator Commercial licenses may use this 
** file in accordance with the Formulator Commercial License Agreement 
** provided with the Software or, alternatively, in accordance with the 
** terms contained in a written agreement between you and 
** Hermitech Laboratory.
**
** GNU General Public License Usage
** Alternatively, this file may be used under the terms of the GNU
** General Public License version 3.0 as published by the Free Software
** Foundation and appearing in the file LICENSE.GPL included in the
** packaging of this file.  Please review the following information to
** ensure the GNU General Public License version 3.0 requirements will be
** met: http://www.gnu.org/copyleft/gpl.html.
**
** If you have questions regarding the use of this file, please contact
** Hermitech Laboratory at info@mmlsoft.com.
**
****************************************************************************/

#include "mml_tag2mml.h"
#include "mml_operator.h"

// 改用纯struct数组,避免VS2019在Release编译极为缓慢

HMathOpAttr HMathOpAttr_OperatorDictionary[ HMathOpAttr_OPERATOR_NUMBER ] =
{ 
	{_T("&hairsp;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("1-point space"),	-1, mmlPrecedence_Atom},
	{_T("&thinsp;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("thin space"),	-1, mmlPrecedence_Atom},
	{_T("&ThinSpace;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("thin space"),	-1, mmlPrecedence_Atom},
	{_T("&VeryThinSpace;"),		HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("very thin space"),	-1, mmlPrecedence_Atom},
	{_T("&ThickSpace;"),		HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("thick space"),	-1, mmlPrecedence_Atom},
	{_T("&ZeroWidthSpace;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("zero width space"),	-1, mmlPrecedence_Atom},
	{_T("&emsp13;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("thick space"),	-1, mmlPrecedence_Atom},
	{_T("&emsp14;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("emsp14"),	-1, mmlPrecedence_Atom},
	{_T("&emsp;"),		HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("em space"),	-1, mmlPrecedence_Atom},
	{_T("&ensp;"),		HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("en space"),	-1, mmlPrecedence_Atom},
	{_T("&MediumSpace;"),		HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("medium space"),	-1, mmlPrecedence_Atom},
	{_T("&nbsp;"),		HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("nbsp space"),	-1, mmlPrecedence_Atom},
	{_T("&NonBreakingSpace;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("nbsp space"),	-1, mmlPrecedence_Atom},

	{_T("("),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ("),	1, mmlPrecedence_Atom},
	{_T(")"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text )"),	1, mmlPrecedence_Atom},
	{_T("["),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ["),	1, mmlPrecedence_Atom},
	{_T("]"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ]"),	1, mmlPrecedence_Atom},
	{_T("{"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text {"),	1, mmlPrecedence_Atom},
	{_T("}"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text }"),	1, mmlPrecedence_Atom},
	{_T("&langle;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text <"),	1, mmlPrecedence_Atom},
	{_T("&lang;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text <"),	1, mmlPrecedence_Atom},
	{_T("&rangle;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text >"),	1, mmlPrecedence_Atom},
	{_T("&rang;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text >"),	1, mmlPrecedence_Atom},
	{_T("&quot;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("\""),	1, mmlPrecedence_Atom},
	{_T("\""),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("\""),	1, mmlPrecedence_Atom},
	{_T("&OpenCurlyDoubleQuote;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&OpenCurlyQuote;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&CloseCurlyDoubleQuote;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&CloseCurlyQuote;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("|"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("text |"),	1, mmlPrecedence_Atom},
	{_T("&verbar;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text |"),	1, mmlPrecedence_Atom},
	{_T("&Verbar;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ||"),	1, mmlPrecedence_Atom},
	{_T("&Verbar;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ||"),	1, mmlPrecedence_Atom},
	{_T("&Vert;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ||"),	1, mmlPrecedence_Atom},
	{_T("&Vert;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ||"),	1, mmlPrecedence_Atom},
	{_T("&lfloor;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("@lfloor"),	1, mmlPrecedence_Atom},
	{_T("&rfloor;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("@rfloor"),	1, mmlPrecedence_Atom},
	{_T("&lceil;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("@lceil"),	1, mmlPrecedence_Atom},
	{_T("&rceil;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("@rceil"),	1, mmlPrecedence_Atom},
	{_T("&VerticalLine;"),	HMathOpAttr_FORM_INFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text |"),	HMathOpAttr_MINSIZE_NULL, mmlPrecedence_Atom}, //{ _T("&VerticalLine;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("|"),	HMathOpAttr_MINSIZE_NULL, mmlPrecedence_Atom },
	{_T("&vert;"),	HMathOpAttr_FORM_INFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text |"),	HMathOpAttr_MINSIZE_NULL, mmlPrecedence_Atom}, //{ _T("&vert;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("|"),	HMathOpAttr_MINSIZE_NULL, mmlPrecedence_Atom },
	{_T("&verbar;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text |"),	1, mmlPrecedence_Atom},
	{_T("_"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("_"),	1, mmlPrecedence_Atom},
	{_T("&lowbar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("_"),	1, mmlPrecedence_Atom},

	{_T("&LeftCeiling;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("@lceil"),	1, mmlPrecedence_Atom},
	{_T("&RightCeiling;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("@rceil"),	1, mmlPrecedence_Atom},
	{_T("&LeftFloor;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("@lfloor"),	1, mmlPrecedence_Atom},
	{_T("&RightFloor;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("@rfloor"),	1, mmlPrecedence_Atom},
	{_T("&LeftAngleBracket;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text <"),	1, mmlPrecedence_Atom},
	{_T("&LeftBracketingBar;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text |"),	1, mmlPrecedence_Atom},
	{_T("&LeftDoubleBracket;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("["),	1, mmlPrecedence_Atom},
	{_T("&LeftDoubleBracketingBar;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ||"),	1, mmlPrecedence_Atom},
	{_T("&RightAngleBracket;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text >"),	1, mmlPrecedence_Atom},
	{_T("&RightBracketingBar;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text |"),	1, mmlPrecedence_Atom},
	{_T("&RightDoubleBracket;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("]"),	1, mmlPrecedence_Atom},
	{_T("&RightDoubleBracketingBar;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ||"),	1, mmlPrecedence_Atom},
	{_T("&LeftSkeleton;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&RightSkeleton;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&InvisibleComma;"),	HMathOpAttr_FORM_INFIX,	0,	1,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T(","),	HMathOpAttr_FORM_INFIX,	0,	1,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_verythickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&HorizontalLine;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	0.0,	0.0,	_T(""),	HMathOpAttr_MINSIZE_NULL, mmlPrecedence_Atom},
	{_T(";"),	HMathOpAttr_FORM_INFIX,	0,	1,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T(";"),	HMathOpAttr_FORM_POSTFIX,	0,	1,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T(":="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(":="),	1, mmlPrecedence_assign},
	{_T("&Assign;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(":="),	1, mmlPrecedence_assign},
	{MML_OPERATOR_BODY_ASSIGN,	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(":="),	1, mmlPrecedence_assign},
	{_T("&Because;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&there4;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@therefore"),	1, mmlPrecedence_Atom},
	{_T("&Therefore;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@therefore"),	1, mmlPrecedence_Atom},
	{_T("&VerticalSeparator;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("//"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&Colon;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("*="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq},
	{_T("-="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq},
	{_T("+="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq},
	{_T("/="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq},
	{_T("->"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T(":"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T(".."),	HMathOpAttr_FORM_POSTFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("..."),	HMathOpAttr_FORM_POSTFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&SuchThat;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DoubleLeftTee;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DoubleRightTee;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DownTee;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LeftTee;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&RightTee;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&Implies;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_implies},
	{_T("&RoundImplies;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_implies},
	{_T("||"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T(""),	1, mmlPrecedence_and},
	{_T("&or;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("|"),	1, mmlPrecedence_and},
	{_T("&Or;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("|"),	1, mmlPrecedence_and},
	{_T("&amp;&amp;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_and},
	{_T("&"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&amp;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&and;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("&"),	1, mmlPrecedence_and},
	{_T("&And;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("&"),	1, mmlPrecedence_and},
	{_T("&amp;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&amp;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("!"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	0.0,	_T(""),	1, mmlPrecedence_unary},
	{_T("!"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_unary},
	{_T("&not;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T("!"),	1, mmlPrecedence_unary},
	{_T("&Not;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T("!"),	1, mmlPrecedence_unary},
	{_T("&exist;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T("@exist"),	1, mmlPrecedence_Last},
	{_T("&Exists;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T("@exist"),	1, mmlPrecedence_Last},
	{_T("&forall;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T("@forall"),	1, mmlPrecedence_Last},
	{_T("&ForAll;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T("@forall"),	1, mmlPrecedence_Last},
	{_T("&NotExists;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Last},
	{_T("&Element;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@in"),	1, mmlPrecedence_in},
	{_T("&NotElement;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@not_in"),	1, mmlPrecedence_in},
	{_T("&NotReverseElement;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in},
	{_T("&NotSquareSubset;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in},
	{_T("&NotSquareSubsetEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in},
	{_T("&NotSquareSuperset;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in},
	{_T("&NotSquareSupersetEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in},
	{_T("&NotSubset;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_not_in"),	1, mmlPrecedence_in},
	{_T("&NotSubsetEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_not_in_eq"),	1, mmlPrecedence_in},
	{_T("&nsube;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_not_in_eq"),	1, mmlPrecedence_in},
	{_T("&nsubE;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_not_in_eq"),	1, mmlPrecedence_in},
	{_T("&nsubseteq;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_not_in_eq"),	1, mmlPrecedence_in},
	{_T("&nsubseteqq;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_not_in_eq"),	1, mmlPrecedence_in},
	{_T("&NotSuperset;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in},
	{_T("&NotSupersetEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in},
	{_T("&subnE;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_with_not_in_eq"),	1, mmlPrecedence_in},
	{_T("&supnE;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_with_not_in_eq_inv"),	1, mmlPrecedence_in},
	{_T("&bsim;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T("reversed ~"),	1, mmlPrecedence_Atom},
	{_T("&bcong;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("all_equal_to"),	1, mmlPrecedence_Atom},
	{_T("&ReverseElement;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in},
	{_T("&SquareSubset;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in},
	{_T("&SquareSubsetEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in},
	{_T("&SquareSuperset;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in},
	{_T("&SquareSupersetEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in},
	{_T("&Subset;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_in"),	1, mmlPrecedence_in},
	{_T("&SubsetEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in},
	{_T("&vltri;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@normal_subgroup"),	1, mmlPrecedence_in},
	{_T("&vrtri;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@cnormal_subgroup"),	1, mmlPrecedence_in},
	{_T("&Superset;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_in_inv"),	1, mmlPrecedence_in},
	{_T("&SupersetEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in},
	{_T("&DoubleLeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DoubleLeftRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DoubleRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DownLeftRightVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DownLeftTeeVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&lhard;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@harpoon_ld"),	1, mmlPrecedence_Atom},
	{_T("&leftharpoondown;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@harpoon_ld"),	1, mmlPrecedence_Atom},
	{_T("&DownLeftVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@harpoon_ld"),	1, mmlPrecedence_Atom},
	{_T("&DownLeftVectorBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DownRightTeeVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DownRightVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DownRightVectorBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&larr;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_l"),	1, mmlPrecedence_Atom},
	{_T("&leftarrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_l"),	1, mmlPrecedence_Atom},
	{_T("&LeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_l"),	1, mmlPrecedence_Atom},
	{_T("&ShortLeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_l"),	1, mmlPrecedence_Atom},
	{_T("&slarr;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_l"),	1, mmlPrecedence_Atom},
	{_T("&LeftArrowBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LeftArrowRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&harr;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_h"),	1, mmlPrecedence_Atom},
	{_T("&leftrightarrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_h"),	1, mmlPrecedence_Atom},
	{_T("&LeftRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_h"),	1, mmlPrecedence_Atom},
	{_T("&LeftRightVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LeftTeeArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LeftTeeVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LeftVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LeftVectorBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LowerLeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LowerRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&rarr;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_r"),	1, mmlPrecedence_Atom},
	{_T("&rightarrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_r"),	1, mmlPrecedence_Atom},
	{_T("&RightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_r"),	1, mmlPrecedence_Atom},
	{_T("&ShortRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_r"),	1, mmlPrecedence_Atom},
	{_T("&srarr;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_r"),	1, mmlPrecedence_Atom},
	{_T("&RightArrowBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&RightArrowLeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&RightTeeArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&RightTeeVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&rharu;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@harpoon_ru"),	1, mmlPrecedence_Atom},
	{_T("&rightharpoonup;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@harpoon_ru"),	1, mmlPrecedence_Atom},
	{_T("&RightVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@harpoon_ru"),	1, mmlPrecedence_Atom},
	{_T("&RightVectorBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&ShortLeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&ShortRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&UpperLeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&UpperRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@assign_eq"),	1, mmlPrecedence_eq},
	{_T("&lt;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("<"),	1, mmlPrecedence_gt},
	{_T("<"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("<"),	1, mmlPrecedence_gt},
	{_T("&Lt;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("<<"),	1, mmlPrecedence_gt},
	{_T("&gt;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(">"),	1, mmlPrecedence_gt},
	{_T(">"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(">"),	1, mmlPrecedence_gt},
	{_T("&Gt;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(">>"),	1, mmlPrecedence_gt},
	{_T("!="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("!="),	1, mmlPrecedence_eq},
	{_T("&ne;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("!="),	1, mmlPrecedence_eq},
	{_T("=="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq},
	{_T("&equiv;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@identical"),	1, mmlPrecedence_eq},
	{_T("&lt;="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(">="),	1, mmlPrecedence_geq},
	{_T(">="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(">="),	1, mmlPrecedence_geq},
	{_T("&Congruent;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq},
	{_T("&CupCap;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DotEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@approaches"),	1, mmlPrecedence_eq},
	{_T("&esdot;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&wedgeq;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@estimates"),	1, mmlPrecedence_eq},
	{_T("&trie;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@delta_equal"),	1, mmlPrecedence_Atom},
	{_T("&spar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("par text ||"),	1, mmlPrecedence_Atom},
	{_T("&DoubleVerticalBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("par text ||"),	1, mmlPrecedence_Atom},
	{_T("&par;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("par text ||"),	1, mmlPrecedence_Atom},
	{_T("&parallel;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("par text ||"),	1, mmlPrecedence_Atom},
	{_T("&shortparallel;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("par text ||"),	1, mmlPrecedence_Atom},
	{_T("&Equal;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq},
	{_T("&EqualTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq},
	{_T("&Equilibrium;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq},
	{_T("&GreaterEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq},
	{_T("&GreaterEqualLess;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq},
	{_T("&GreaterFullEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq},
	{_T("&GreaterGreater;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&GreaterLess;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&GreaterSlantEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq},
	{_T("&GreaterTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&HumpDownHump;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&HumpEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LeftTriangle;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LeftTriangleBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LeftTriangleEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&le;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("<="),	1, mmlPrecedence_geq},
	{_T("&ge;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(">="),	1, mmlPrecedence_geq},
	{_T("&LessEqualGreater;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq},
	{_T("&LessFullEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq},
	{_T("&LessGreater;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq},
	{_T("&LessLess;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&LessSlantEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq},
	{_T("&LessTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&NestedGreaterGreater;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&NestedLessLess;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&NotCongruent;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq},
	{_T("&NotCupCap;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotDoubleVerticalBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("!="),	1, mmlPrecedence_eq},
	{_T("&NotEqualTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq},
	{_T("&NotGreater;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&NotGreaterEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq},
	{_T("&NotGreaterFullEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq},
	{_T("&NotGreaterGreater;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&NotGreaterLess;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&NotGreaterSlantEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq},
	{_T("&NotGreaterTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&NotHumpDownHump;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotHumpEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq},
	{_T("&NotLeftTriangle;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotLeftTriangleBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotLeftTriangleEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq},
	{_T("&NotLess;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&NotLessEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq},
	{_T("&NotLessFullEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq},
	{_T("&NotLessGreater;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&NotLessLess;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&NotLessSlantEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq},
	{_T("&NotLessTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&NotNestedGreaterGreater;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&NotNestedLessLess;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt},
	{_T("&NotPrecedes;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotPrecedesEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotPrecedesSlantEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotPrecedesTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotRightTriangle;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotRightTriangleBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotRightTriangleEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotSucceeds;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotSucceedsEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotSucceedsSlantEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotSucceedsTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotTildeEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotTildeFullEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotTildeTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&NotVerticalBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&Precedes;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@precedes"),	1, mmlPrecedence_Atom},
	{_T("&PrecedesEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&PrecedesSlantEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&PrecedesTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&Proportion;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&prop;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@proportional"),	1, mmlPrecedence_Atom},
	{_T("&Proportional;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@proportional"),	1, mmlPrecedence_Atom},
	{_T("&ReverseEquilibrium;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&RightTriangle;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&RightTriangleBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&RightTriangleEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&Succeeds;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@succeeds"),	1, mmlPrecedence_Atom},
	{_T("&SucceedsEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&SucceedsSlantEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&SucceedsTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&sim;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("~"),	1, mmlPrecedence_Atom},
	{_T("&Tilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("~"),	1, mmlPrecedence_Atom},
	{_T("&tilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T("~"),	1, mmlPrecedence_Atom},
	{_T("~"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("~"),	1, mmlPrecedence_Atom},
	{_T("&TildeEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("~-"),	1, mmlPrecedence_Atom},
	{_T("&sime;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("~-"),	1, mmlPrecedence_Atom},
	{_T("&cong;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("~="),	1, mmlPrecedence_Atom},
	{_T("&TildeFullEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("~="),	1, mmlPrecedence_Atom},
	{_T("&ap;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@almost_equal"),	1, mmlPrecedence_Atom},
	{_T("&TildeTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@almost_equal"),	1, mmlPrecedence_Atom},
	{_T("&UpTee;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&VerticalBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&SquareUnion;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T(""),	1, mmlPrecedence_intersect},
	{_T("&Union;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@sadd"),	1, mmlPrecedence_intersect},
	{_T("&UnionPlus;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T(""),	1, mmlPrecedence_intersect},
	{_T("&minus;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@minus"),	1, mmlPrecedence_add},
	{_T("-"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@minus"),	1, mmlPrecedence_add},
	{_T("+"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@plus"),	1, mmlPrecedence_add},
	{_T("&plus;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@plus"),	1, mmlPrecedence_add},
	{_T("&Intersection;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@smul"),	1, mmlPrecedence_intersect},
	{_T("&MinusPlus;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T(""),	1, mmlPrecedence_add},
	{_T("&PlusMinus;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@plusminus"),	1, mmlPrecedence_add},
	{_T("&SquareIntersection;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T(""),	1, mmlPrecedence_intersect},
	{_T("&Vee;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&CircleMinus;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_add},
	{_T("&CirclePlus;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@circle_plus"),	1, mmlPrecedence_add},
	{_T("&oplus;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@circle_plus"),	1, mmlPrecedence_add},
	{_T("&sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum"),	1, mmlPrecedence_Atom},
	{_T("&Sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum"),	1, mmlPrecedence_Atom},
	{_T("&sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_nl"),	1, mmlPrecedence_Atom},
	{_T("&Sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_nl"),	1, mmlPrecedence_Atom},
	{_T("&sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_ul"),	1, mmlPrecedence_Atom},
	{_T("&Sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_ul"),	1, mmlPrecedence_Atom},
	{_T("&sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_uol"),	1, mmlPrecedence_Atom},
	{_T("&Sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_uol"),	1, mmlPrecedence_Atom},
	{_T("&sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_subl"),	1, mmlPrecedence_Atom},
	{_T("&Sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_subl"),	1, mmlPrecedence_Atom},
	{_T("&sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_subsupl"),	1, mmlPrecedence_Atom},
	{_T("&Sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_subsupl"),	1, mmlPrecedence_Atom},
	{_T("&Union;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@union_nl"),	1, mmlPrecedence_intersect},
	{_T("&Union;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@union_ul"),	1, mmlPrecedence_intersect},
	{_T("&Union;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@union_uol"),	1, mmlPrecedence_intersect},
	{_T("&Union;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@union_subl"),	1, mmlPrecedence_intersect},
	{_T("&Union;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@union_subsupl"),	1, mmlPrecedence_intersect},
	{_T("&UnionPlus;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_intersect},
	{_T("lim"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	1,	0,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("max"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	1,	0,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("min"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	1,	0,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&CircleMinus;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	0,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@circle_minus"),	1, mmlPrecedence_add},
	{_T("&CirclePlus;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	0,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@circle_plus"),	1, mmlPrecedence_add},
	{_T("&int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral"),	1, mmlPrecedence_Atom},
	{_T("&cwconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cwintegral"),	1, mmlPrecedence_Atom},
	{_T("&conint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cintegral"),	1, mmlPrecedence_Atom},
	{_T("&awconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@awintegral"),	1, mmlPrecedence_Atom},
	{_T("&Conint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@aintegral"),	1, mmlPrecedence_Atom},
	{_T("&Int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@dintegral"),	1, mmlPrecedence_Atom},
	{_T("&tint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@tintegral"),	1, mmlPrecedence_Atom},
	{_T("&Cconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@vintegral"),	1, mmlPrecedence_Atom},
	{_T("&ClockwiseContourIntegral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cwintegral_nl"),	1, mmlPrecedence_Atom},
	{_T("&ClockwiseContourIntegral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cwintegral_ul"),	1, mmlPrecedence_Atom},
	{_T("&ClockwiseContourIntegral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cwintegral_subl"),	1, mmlPrecedence_Atom},
	{_T("&cwconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cwintegral_nl"),	1, mmlPrecedence_Atom},
	{_T("&cwconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cwintegral_ul"),	1, mmlPrecedence_Atom},
	{_T("&cwconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cwintegral_subl"),	1, mmlPrecedence_Atom},
	{_T("&conint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cintegral_nl"),	1, mmlPrecedence_Atom},
	{_T("&conint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cintegral_ul"),	1, mmlPrecedence_Atom},
	{_T("&conint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cintegral_subl"),	1, mmlPrecedence_Atom},
	{_T("&awconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@awintegral_nl"),	1, mmlPrecedence_Atom},
	{_T("&awconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@awintegral_ul"),	1, mmlPrecedence_Atom},
	{_T("&awconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@awintegral_subl"),	1, mmlPrecedence_Atom},
	{_T("&Conint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@aintegral_nl"),	1, mmlPrecedence_Atom},
	{_T("&Conint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@aintegral_ul"),	1, mmlPrecedence_Atom},
	{_T("&Conint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@aintegral_subl"),	1, mmlPrecedence_Atom},
	{_T("&Integral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral"),	1, mmlPrecedence_Atom},
	{_T("&int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_nl"),	1, mmlPrecedence_Atom},
	{_T("&Integral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_nl"),	1, mmlPrecedence_Atom},
	{_T("&Integral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_ul"),	1, mmlPrecedence_Atom},
	{_T("&int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_ul"),	1, mmlPrecedence_Atom},
	{_T("&Integral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_uol"),	1, mmlPrecedence_Atom},
	{_T("&int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_uol"),	1, mmlPrecedence_Atom},
	{_T("&Integral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_subl"),	1, mmlPrecedence_Atom},
	{_T("&int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_subl"),	1, mmlPrecedence_Atom},
	{_T("&Integral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_subsupl"),	1, mmlPrecedence_Atom},
	{_T("&int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_subsupl"),	1, mmlPrecedence_Atom},
	{_T("&Int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@dintegral_nl"),	1, mmlPrecedence_Atom},
	{_T("&Int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@dintegral_ul"),	1, mmlPrecedence_Atom},
	{_T("&Int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@dintegral_subl"),	1, mmlPrecedence_Atom},
	{_T("&tint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@tintegral_nl"),	1, mmlPrecedence_Atom},
	{_T("&tint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@tintegral_ul"),	1, mmlPrecedence_Atom},
	{_T("&tint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@tintegral_subl"),	1, mmlPrecedence_Atom},
	{_T("&Cconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@vintegral_nl"),	1, mmlPrecedence_Atom},
	{_T("&Cconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@vintegral_ul"),	1, mmlPrecedence_Atom},
	{_T("&Cconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@vintegral_subl"),	1, mmlPrecedence_Atom},
	{_T("&isin;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@in"),	1, mmlPrecedence_Atom},
	{_T("&isinv;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@in"),	1, mmlPrecedence_Atom},
	{_T("&notin;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@not_in"),	1, mmlPrecedence_in},
	{_T("&sub;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@set_in"),	1, mmlPrecedence_Atom},
	{_T("&sup;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@set_in_inv"),	1, mmlPrecedence_Atom},
	{_T("&subE;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@set_in_eq"),	1, mmlPrecedence_Atom},
	{_T("&supE;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@set_in_eq_inv"),	1, mmlPrecedence_Atom},
	{_T("&vnsub;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@set_not_in"),	1, mmlPrecedence_Atom},
	{_T("&emptyv;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@set_empty"),	1, mmlPrecedence_Atom},
	{_T("&Cup;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@sadd"),	1, mmlPrecedence_intersect},
	{_T("&Cap;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@smul"),	1, mmlPrecedence_intersect},
	{_T("&cup;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@sadd"),	1, mmlPrecedence_intersect},
	{_T("&cap;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@smul"),	1, mmlPrecedence_intersect},
	{_T("&VerticalTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&Wedge;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&CircleTimes;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@circle_times"),	1, mmlPrecedence_mult},
	{_T("&otimes;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@circle_times"),	1, mmlPrecedence_mult},
	{_T("&coprod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct"),	1, mmlPrecedence_Atom},
	{_T("&Coproduct;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct"),	1, mmlPrecedence_Atom},
	{_T("&Coproduct;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_nl"),	1, mmlPrecedence_Atom},
	{_T("&coprod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_nl"),	1, mmlPrecedence_Atom},
	{_T("&Coproduct;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_ul"),	1, mmlPrecedence_Atom},
	{_T("&coprod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_ul"),	1, mmlPrecedence_Atom},
	{_T("&Coproduct;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_uol"),	1, mmlPrecedence_Atom},
	{_T("&coprod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_uol"),	1, mmlPrecedence_Atom},
	{_T("&Coproduct;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_subl"),	1, mmlPrecedence_Atom},
	{_T("&coprod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_subl"),	1, mmlPrecedence_Atom},
	{_T("&Coproduct;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_subsupl"),	1, mmlPrecedence_Atom},
	{_T("&coprod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_subsupl"),	1, mmlPrecedence_Atom},
	{_T("&prod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product"),	1, mmlPrecedence_Atom},
	{_T("&Product;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product"),	1, mmlPrecedence_Atom},
	{_T("&Product;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_nl"),	1, mmlPrecedence_Atom},
	{_T("&prod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_nl"),	1, mmlPrecedence_Atom},
	{_T("&Product;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_ul"),	1, mmlPrecedence_Atom},
	{_T("&prod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_ul"),	1, mmlPrecedence_Atom},
	{_T("&Product;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_uol"),	1, mmlPrecedence_Atom},
	{_T("&prod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_uol"),	1, mmlPrecedence_Atom},
	{_T("&Product;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_subl"),	1, mmlPrecedence_Atom},
	{_T("&prod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_subl"),	1, mmlPrecedence_Atom},
	{_T("&Product;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_subsupl"),	1, mmlPrecedence_Atom},
	{_T("&prod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_subsupl"),	1, mmlPrecedence_Atom},
	{_T("&Coproduct;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct"),	1, mmlPrecedence_Atom},
	{_T("&coprod;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct"),	1, mmlPrecedence_Atom},
	{_T("&Product;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@product"),	1, mmlPrecedence_Atom},
	{_T("&prod;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@product"),	1, mmlPrecedence_Atom},
	{_T("&Intersection;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@intersection_nl"),	1, mmlPrecedence_Atom},
	{_T("&Intersection;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@intersection_ul"),	1, mmlPrecedence_Atom},
	{_T("&Intersection;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@intersection_uol"),	1, mmlPrecedence_Atom},
	{_T("&Intersection;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@intersection_subl"),	1, mmlPrecedence_Atom},
	{_T("&Intersection;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@intersection_subsupl"),	1, mmlPrecedence_Atom},
	{_T("&Star;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_mult},
	{_T("&CenterDot;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@center_dot"),	1, mmlPrecedence_mult},
	{_T("&sdot;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@center_dot"),	1, mmlPrecedence_mult},
	{_T("*"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("*"),	1, mmlPrecedence_mult},
	{_T("&lowast;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("*"),	1, mmlPrecedence_Atom},
	{_T("&times;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@times"),	1, mmlPrecedence_Atom},
	{_T("&InvisibleTimes;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_mult},
	{_T("&bull;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@bullet"),	1, mmlPrecedence_Atom},
	{_T("&CircleDot;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	0,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_mult},
	{_T("&CircleTimes;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	0,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@circle_times"),	1, mmlPrecedence_mult},
	{_T("&Vee;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&Wedge;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&Diamond;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&Backslash;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&sol;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("text /"),	1, mmlPrecedence_mult},
	{_T("/"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("text /"),	1, mmlPrecedence_mult},
	{_T("&divide;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@divide"),	1, mmlPrecedence_mult},
	{_T("-"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_veryverythinmathspace,	_T("@minus"),	1, mmlPrecedence_add},
	{_T("+"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_veryverythinmathspace,	_T(""),	1, mmlPrecedence_add},
	{_T("&MinusPlus;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_veryverythinmathspace,	_T(""),	1, mmlPrecedence_add},
	{_T("&PlusMinus;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_veryverythinmathspace,	_T(""),	1, mmlPrecedence_add},
	{_T("."),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&Cross;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("**"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&CircleDot;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_mult},
	{_T("&SmallCircle;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&Square;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&Del;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&PartialD;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_verythinmathspace,	_T("@partiald"),	1, mmlPrecedence_Atom},
	{_T("&CapitalDifferentialD;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_verythinmathspace,	_T("@capitaldifferentiald"),	1, mmlPrecedence_Atom},
	{_T("&DifferentialD;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_verythinmathspace,	_T("@differentiald"),	1, mmlPrecedence_Atom},
	{_T("&Sqrt;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	1,	0.0,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DoubleDownArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DoubleLongLeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DoubleLongLeftRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DoubleLongRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DoubleUpArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DoubleUpDownArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DownArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DownArrowBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DownArrowUpArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DownTeeArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LeftDownTeeVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LeftDownVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LeftDownVectorBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LeftUpDownVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LeftUpTeeVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LeftUpVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LeftUpVectorBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LongLeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LongLeftRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&LongRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&ReverseUpEquilibrium;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&RightDownTeeVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&RightDownVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&RightDownVectorBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&RightUpDownVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&RightUpTeeVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&RightUpVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&RightUpVectorBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&ShortDownArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&ShortUpArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&UpArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&UpArrowBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&UpArrowDownArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&UpDownArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&UpEquilibrium;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&UpTeeArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&circ;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("^"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&lt;>"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_geq},
	{_T("\'"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("!!"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&commat;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("@"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("--"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("--"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("++"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("++"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&ApplyFunction;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@apply_function"),	1, mmlPrecedence_apply},
	{_T("&af;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@apply_function"),	1, mmlPrecedence_apply},
	{_T("&InvisibleTimes;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@invisible_times"),	1, mmlPrecedence_mult},
	{_T("&it;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@invisible_times"),	1, mmlPrecedence_mult},
	{_T("&InvisibleComma;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@invisible_coma"),	1, mmlPrecedence_Atom},
	{_T("&ic;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@invisible_coma"),	1, mmlPrecedence_Atom},
	{_T("?"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("_"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&Breve;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&Cedilla;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DiacriticalGrave;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DiacriticalDot;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DiacriticalDoubleAcute;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DiacriticalLeftArrow;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DiacriticalLeftRightArrow;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DiacriticalLeftRightVector;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DiacriticalLeftVector;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DiacriticalAcute;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DiacriticalRightArrow;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DiacriticalRightVector;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DiacriticalTilde;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DoubleDot;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&DownBreve;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&Hacek;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&Hat;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&macr;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&OverBar;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&OverBrace;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T("@overbrace"),	1, mmlPrecedence_Atom},
	{_T("&tcub;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T("@overbrace"),	1, mmlPrecedence_Atom},
	{_T("&OverBracket;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&OverParenthesis;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&TripleDot;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&UnderBar;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T("text _"),	1, mmlPrecedence_Atom},
	{_T("&UnderBrace;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T("@underbrace"),	1, mmlPrecedence_Atom},
	{_T("&bcub;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T("@underbrace"),	1, mmlPrecedence_Atom},
	{_T("&UnderBracket;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&UnderParenthesis;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{_T("&marker;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@nop"),	1, mmlPrecedence_Atom},
	{_T("&ExponentialE;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@exp"),	1, mmlPrecedence_Atom},
	{_T("&exponentiale;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@exp"),	1, mmlPrecedence_Atom},
	{_T("&ee;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@exp"),	1, mmlPrecedence_Atom},
	{_T("&frown;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom},
	{QChar(0x2212),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@minus"),	1, mmlPrecedence_add},
	{ QChar(0x2212),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_veryverythinmathspace,	_T("@minus"),	1, mmlPrecedence_add }
};